package com.example.platform

object DefaultFeatureCatalog {

    val INITIAL_CHANGELOGS: List<ChangelogEntry> = listOf(
        ChangelogEntry(
            version = "2.3.0",
            releaseDate = "2026-09-28",
            headline = "Dynamic Feature Registry, AI Model Router & 28-Category AI Tool Hub",
            newItems = listOf(
                "Dynamic Feature Management System — Founder can create, configure, release, and roll back AI tools live",
                "AI Model Router with automatic Primary → Secondary AI Provider Fallback",
                "Expanded 28-Category AI Tool Hub including AI Presentation Generator, AI Data Analysis, AI OCR, AI Agent & Automation",
                "Feature Flag Engine with percentage rollouts (10% → 25% → 50% → 100%) and plan gating",
                "Real-time App Update Manager with Semantic Versioning (MAJOR.MINOR.PATCH) & What's New discovery"
            ),
            improvedItems = listOf(
                "Faster streaming responses with automatic model routing",
                "Enhanced multimodal file, PDF, and vision analysis accuracy",
                "Upgraded Room database to v2 with non-destructive migration preserving all user data"
            ),
            fixedItems = listOf(
                "Fixed chat history folder filtering and instant search responsiveness",
                "Resolved image generation aspect ratio preview scaling on compact screens"
            ),
            securityItems = listOf(
                "Server-side API key protection with zero secret exposure in frontend UI",
                "Added Founder Admin Role verification, rate limiting, and security audit logging"
            )
        ),
        ChangelogEntry(
            version = "2.1.0",
            releaseDate = "2026-09-15",
            headline = "Veo 3 Video Studio, Lyria 3 Music Lab & Founder Voice Onboarding",
            newItems = listOf(
                "AI Video Generator powered by Veo 3 (16:9 & 9:16)",
                "Improved AI Image Studio with text-to-image & photo editing",
                "New Live Voice Mode & Founder Voice Introduction",
                "Lyria 3 AI Audio & Music Generation Studio"
            ),
            improvedItems = listOf(
                "Faster multi-turn chat streaming with Markdown & code syntax blocks",
                "Cloud-synced Personal AI Workspace & Prompt Library"
            ),
            fixedItems = listOf(
                "Fixed audio playback pause/resume state synchronization",
                "Resolved daily quota counter reset across UTC midnight boundaries"
            ),
            securityItems = listOf(
                "Hardened Cloud Firestore per-user ownership and schema validation rules"
            )
        ),
        ChangelogEntry(
            version = "1.0.0",
            releaseDate = "2026-08-01",
            headline = "Initial Production Launch of Kallesh AI Hub",
            newItems = listOf(
                "Multi-model AI Chat with persistent conversations, pinning, folders, and sharing",
                "Google Sign-In authentication & Free / Pro / Enterprise subscription tiers"
            ),
            improvedItems = listOf(
                "Responsive Material 3 dark & light theme adaptive layout"
            ),
            fixedItems = listOf(
                "Initial release stability and offline Room caching"
            ),
            securityItems = listOf(
                "Encrypted Firebase Auth session management"
            )
        )
    )

    val BUILT_IN_FEATURES: List<PlatformFeature> = listOf(
        PlatformFeature(
            featureId = "feat_ai_chat",
            name = "Kallesh Multi-Model AI Chat",
            description = "Streaming conversational AI with Markdown, code blocks, file attachments, pinning, and folders.",
            howToUse = "Open the Chat tab, select your preferred AI model, type or speak your prompt, and stream instant responses.",
            iconKey = "chat",
            category = AiToolCategory.AI_CHAT,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://section/chat",
            taskType = AiRouterTaskType.CHAT,
            systemInstruction = "You are Kallesh AI Hub's flagship conversational assistant. Provide accurate, well-structured Markdown answers.",
            inputPlaceholder = "Ask anything or start a multi-turn conversation..."
        ),
        PlatformFeature(
            featureId = "feat_ai_search",
            name = "AI Grounded Live Search",
            description = "Real-time web search grounded answers with verified source citations and live facts.",
            howToUse = "Enter a question about current events, documentation, or live facts to receive grounded answers with source links.",
            iconKey = "search",
            category = AiToolCategory.AI_SEARCH,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent?grounding=googleSearch",
            frontendRoute = "hub://tool/feat_ai_search",
            taskType = AiRouterTaskType.SEARCH_RESEARCH,
            systemInstruction = "Perform live grounded search analysis. Synthesize key facts clearly and cite authoritative web sources.",
            inputPlaceholder = "Search live topics, news, benchmarks, or technical docs..."
        ),
        PlatformFeature(
            featureId = "feat_ai_research",
            name = "Deep AI Research Analyst",
            description = "Comprehensive multi-angle literature, market, and scientific synthesis with structured citations.",
            howToUse = "Specify your research topic or hypothesis. The AI router executes grounded synthesis with executive takeaways.",
            iconKey = "science",
            category = AiToolCategory.AI_RESEARCH,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent?grounding=googleSearch",
            frontendRoute = "hub://tool/feat_ai_research",
            taskType = AiRouterTaskType.SEARCH_RESEARCH,
            systemInstruction = "Act as a Senior Principal Research Analyst. Produce an Executive Summary, Methodology, Key Findings, Comparative Matrix, and Citations.",
            inputPlaceholder = "Enter a research topic, industry trend, or scientific question..."
        ),
        PlatformFeature(
            featureId = "feat_image_gen",
            name = "AI Image Generation Studio",
            description = "Generate photorealistic, digital art, 3D, and brand visuals in 1:1, 16:9, 9:16, 4:3, and 3:4.",
            howToUse = "Describe the scene, lighting, and style, choose an aspect ratio, and generate studio-grade artwork.",
            iconKey = "image",
            category = AiToolCategory.AI_IMAGE_GEN,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            dailyLimitFree = 3,
            dailyLimitPro = 25,
            dailyLimitPremium = 100,
            backendEndpoint = "/v1beta/models/gemini-3.1-flash-image-preview:generateContent",
            frontendRoute = "hub://studio/image",
            taskType = AiRouterTaskType.IMAGE_GEN,
            systemInstruction = "Generate high-resolution visual artwork matching the user's prompt.",
            inputPlaceholder = "Describe the image you want to create..."
        ),
        PlatformFeature(
            featureId = "feat_image_edit",
            name = "AI Photo Editor & Restyler",
            description = "Upload an existing image and transform, retouch, or restyle it with natural-language instructions.",
            howToUse = "Attach a reference photo in AI Image Studio or this tool and describe the visual modifications.",
            iconKey = "brush",
            category = AiToolCategory.AI_IMAGE_EDIT,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            dailyLimitFree = 3,
            dailyLimitPro = 25,
            dailyLimitPremium = 100,
            backendEndpoint = "/v1beta/models/gemini-3.1-flash-image-preview:generateContent",
            frontendRoute = "hub://studio/image",
            taskType = AiRouterTaskType.IMAGE_GEN,
            systemInstruction = "Edit and transform the provided image according to the user's instructions.",
            inputPlaceholder = "Describe how to edit or restyle your image..."
        ),
        PlatformFeature(
            featureId = "feat_video_veo",
            name = "Veo 3 AI Video Generator",
            description = "Create cinematic 16:9 landscape and 9:16 vertical videos from text prompts or reference photos.",
            howToUse = "Open Veo 3 Video Studio, choose 16:9 or 9:16, enter a cinematic prompt, and track real-time rendering.",
            iconKey = "videocam",
            category = AiToolCategory.AI_VIDEO_GEN,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            dailyLimitFree = 1,
            dailyLimitPro = 5,
            dailyLimitPremium = 25,
            backendEndpoint = "/v1beta/models/veo-3.1-fast-generate-preview:predictLongRunning",
            frontendRoute = "hub://studio/video",
            taskType = AiRouterTaskType.VIDEO_GEN,
            systemInstruction = "Generate cinematic motion video using Veo 3.",
            inputPlaceholder = "Describe camera motion, subject, and lighting for your video..."
        ),
        PlatformFeature(
            featureId = "feat_audio_music",
            name = "Lyria 3 AI Audio & Music Lab",
            description = "Compose original 30-second instrumental clips or full-length studio tracks with custom genres and moods.",
            howToUse = "Select genre/mood tags or describe instrumentation and tempo to generate playable WAV audio.",
            iconKey = "music_note",
            category = AiToolCategory.AI_AUDIO_GEN,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.BETA,
            dailyLimitFree = 2,
            dailyLimitPro = 15,
            dailyLimitPremium = 50,
            backendEndpoint = "/v1beta/models/lyria-3-clip-preview:generateContent",
            frontendRoute = "hub://studio/music",
            taskType = AiRouterTaskType.AUDIO_MUSIC,
            systemInstruction = "Compose original studio music matching the requested genre, mood, and instrumentation.",
            inputPlaceholder = "Describe the musical style, instruments, and tempo..."
        ),
        PlatformFeature(
            featureId = "feat_voice_tts",
            name = "Neural AI Voice & TTS Studio",
            description = "Convert scripts and articles into natural studio-quality spoken audio with customizable voice profiles.",
            howToUse = "Enter any text or script and tap Speak Aloud to synthesize studio WAV audio.",
            iconKey = "record_voice_over",
            category = AiToolCategory.AI_VOICE_TTS,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            requiredPermissions = listOf("INTERNET"),
            backendEndpoint = "/v1beta/models/gemini-3.5-flash-tts:generateContent",
            frontendRoute = "hub://studio/voice",
            taskType = AiRouterTaskType.VOICE_TTS,
            systemInstruction = "Synthesize natural human-like spoken audio from the provided text.",
            inputPlaceholder = "Paste script or narration text to synthesize into voice audio..."
        ),
        PlatformFeature(
            featureId = "feat_speech_stt",
            name = "AI Speech-to-Text Transcriber",
            description = "High-accuracy microphone recording and audio transcription with speaker formatting.",
            howToUse = "Open Live Voice & Speech Studio, record audio via microphone, and receive instant text transcription.",
            iconKey = "mic",
            category = AiToolCategory.SPEECH_TO_TEXT,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            requiredPermissions = listOf("INTERNET", "RECORD_AUDIO"),
            backendEndpoint = "/v1beta/models/gemini-3.5-transcribe:generateContent",
            frontendRoute = "hub://studio/voice",
            taskType = AiRouterTaskType.SPEECH_STT,
            systemInstruction = "Transcribe spoken audio accurately into clean, punctuated text.",
            inputPlaceholder = "Record microphone audio or paste raw transcript to clean up..."
        ),
        PlatformFeature(
            featureId = "feat_ai_vision",
            name = "AI Vision & Scene Inspector",
            description = "Attach diagrams, UI screenshots, architecture charts, or photos for deep visual reasoning.",
            howToUse = "Attach an image and ask questions about objects, layout, design critiques, or technical diagrams.",
            iconKey = "visibility",
            category = AiToolCategory.AI_VISION,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_vision",
            taskType = AiRouterTaskType.VISION_OCR,
            systemInstruction = "You are a multimodal Vision AI specialist. Inspect the attached image or diagram in detail and answer with precision.",
            inputPlaceholder = "Attach an image and ask a visual analysis question..."
        ),
        PlatformFeature(
            featureId = "feat_ai_ocr",
            name = "AI Optical Character Recognition (OCR)",
            description = "Extract structured text, tables, receipts, handwriting, and formulas from images into clean Markdown/JSON.",
            howToUse = "Attach a photo of a document, whiteboard, or receipt and run AI OCR extraction.",
            iconKey = "document_scanner",
            category = AiToolCategory.AI_OCR,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_ocr",
            taskType = AiRouterTaskType.VISION_OCR,
            systemInstruction = "Extract 100% of visible text, numbers, tables, and key-value fields from the attached image. Format tables in Markdown.",
            inputPlaceholder = "Attach an image/scan to extract all text and tables..."
        ),
        PlatformFeature(
            featureId = "feat_ai_documents",
            name = "AI Document Intelligence",
            description = "Extract key insights, action items, risks, and structured Q&A from business and legal documents.",
            howToUse = "Upload a document or paste text to generate executive summaries, action items, or contract analysis.",
            iconKey = "description",
            category = AiToolCategory.AI_DOCUMENTS,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_documents",
            taskType = AiRouterTaskType.DOCUMENT_ANALYSIS,
            systemInstruction = "Analyze the document thoroughly. Highlight key clauses, action items, key takeaways, and structured answers.",
            inputPlaceholder = "Attach a document or paste text to analyze..."
        ),
        PlatformFeature(
            featureId = "feat_pdf_analysis",
            name = "AI PDF Deep Analyzer",
            description = "Upload PDF reports, academic papers, or manuals to extract tables, citations, and section summaries.",
            howToUse = "Upload a PDF file using the attachment button and specify what sections or metrics to extract.",
            iconKey = "picture_as_pdf",
            category = AiToolCategory.PDF_ANALYSIS,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_pdf_analysis",
            taskType = AiRouterTaskType.DOCUMENT_ANALYSIS,
            systemInstruction = "You are an expert PDF analyst. Parse the PDF content, summarize each section, and extract structured tables.",
            inputPlaceholder = "Attach a PDF and ask questions about its contents..."
        ),
        PlatformFeature(
            featureId = "feat_file_analysis",
            name = "Multimodal File & CSV/JSON Inspector",
            description = "Inspect structured data files (CSV, JSON, XML, logs, Markdown) for anomalies, schemas, and insights.",
            howToUse = "Attach a file or paste structured data to validate schemas, detect anomalies, and summarize metrics.",
            iconKey = "folder_open",
            category = AiToolCategory.FILE_ANALYSIS,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_file_analysis",
            taskType = AiRouterTaskType.DOCUMENT_ANALYSIS,
            systemInstruction = "Inspect the provided file content, explain its structure, detect anomalies, and provide actionable insights.",
            inputPlaceholder = "Attach a CSV/JSON/log file or paste raw data..."
        ),
        PlatformFeature(
            featureId = "feat_ai_coding",
            name = "Kallesh Code AI Architect",
            description = "Full-stack software architecture, code review, refactoring, and unit test generation across 13+ languages.",
            howToUse = "Paste code or describe a system component to receive clean, production-grade code with complexity analysis.",
            iconKey = "code",
            category = AiToolCategory.AI_CODING,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_ai_coding",
            taskType = AiRouterTaskType.CODING,
            systemInstruction = "You are a Principal Staff Software Engineer. Write clean, idiomatic, well-tested production code with architectural explanations.",
            inputPlaceholder = "Describe the architecture or paste code to review/refactor..."
        ),
        PlatformFeature(
            featureId = "feat_code_debugging",
            name = "AI Bug Hunter & Stacktrace Debugger",
            description = "Diagnose stack traces, memory leaks, concurrency race conditions, and compiler errors with root-cause fixes.",
            howToUse = "Paste your error log, stack trace, and offending code block to get the exact root cause and patched code.",
            iconKey = "bug_report",
            category = AiToolCategory.CODE_DEBUGGING,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_code_debugging",
            taskType = AiRouterTaskType.CODING,
            systemInstruction = "Diagnose the exact root cause of the bug or stack trace, explain why it occurs, and provide the verified fix.",
            inputPlaceholder = "Paste stack trace, compiler error, or buggy code..."
        ),
        PlatformFeature(
            featureId = "feat_code_generation",
            name = "AI Boilerplate & API Generator",
            description = "Generate complete REST/GraphQL endpoints, SQL/Room schemas, Compose UI screens, and CI/CD pipelines.",
            howToUse = "Specify your target language, framework, and data model to generate ready-to-compile modules.",
            iconKey = "terminal",
            category = AiToolCategory.CODE_GENERATION,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_code_generation",
            taskType = AiRouterTaskType.CODING,
            systemInstruction = "Generate complete, production-ready code modules with zero placeholders and full error handling.",
            inputPlaceholder = "Specify language, framework, and feature requirements..."
        ),
        PlatformFeature(
            featureId = "feat_ai_study",
            name = "AI Study & Exam Mastery Tutor",
            description = "Interactive exam prep, flashcards, practice MCQs with answer keys, and step-by-step STEM tutoring.",
            howToUse = "Enter any academic subject or syllabus topic to generate study notes, flashcards, and practice quizzes.",
            iconKey = "school",
            category = AiToolCategory.AI_STUDY_MODE,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_study",
            taskType = AiRouterTaskType.CHAT,
            systemInstruction = "Act as an encouraging expert academic tutor. Break down concepts clearly, provide examples, and include a practice quiz.",
            inputPlaceholder = "Enter a subject, chapter, or exam question..."
        ),
        PlatformFeature(
            featureId = "feat_ai_writing",
            name = "AI Writing & Content Studio",
            description = "Craft executive emails, technical blogs, product launches, essays, and social campaigns.",
            howToUse = "Describe your audience, tone, and topic to generate polished, publication-ready writing.",
            iconKey = "edit_note",
            category = AiToolCategory.AI_WRITING,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_writing",
            taskType = AiRouterTaskType.CHAT,
            systemInstruction = "You are a world-class editor and copywriter. Produce engaging, clear, well-structured writing tailored to the target audience.",
            inputPlaceholder = "Describe what you want to write, target audience, and tone..."
        ),
        PlatformFeature(
            featureId = "feat_ai_translation",
            name = "Neural Multi-Language Translator",
            description = "Context-aware translation across 40+ global and Indian languages (Kannada, Hindi, Tamil, Telugu, Spanish, French, Japanese, etc.).",
            howToUse = "Enter text and specify source/target languages for culturally accurate translations with pronunciation guides.",
            iconKey = "translate",
            category = AiToolCategory.AI_TRANSLATION,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_translation",
            taskType = AiRouterTaskType.CHAT,
            systemInstruction = "Provide natural, idiomatically accurate translations along with phonetic pronunciation and cultural notes when helpful.",
            inputPlaceholder = "Enter text and target language (e.g. English to Kannada)..."
        ),
        PlatformFeature(
            featureId = "feat_ai_summarization",
            name = "AI Executive Summarizer",
            description = "Condense long transcripts, books, research papers, and meeting notes into TL;DR bullets and action tables.",
            howToUse = "Paste long-form text or attach a document to receive a 1-minute executive briefing and key takeaways.",
            iconKey = "summarize",
            category = AiToolCategory.AI_SUMMARIZATION,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_summarization",
            taskType = AiRouterTaskType.DOCUMENT_ANALYSIS,
            systemInstruction = "Condense the input into: 1) One-Sentence TL;DR, 2) Key Executive Bullet Points, 3) Action Items & Decisions.",
            inputPlaceholder = "Paste long article, meeting transcript, or report to summarize..."
        ),
        PlatformFeature(
            featureId = "feat_ai_presentation",
            name = "AI Presentation & Pitch Deck Generator",
            description = "Generate slide-by-slide presentation outlines, speaker scripts, visual prompts, and investor pitch decks.",
            howToUse = "Enter your presentation topic, audience, and number of slides to generate a complete slide deck blueprint.",
            iconKey = "slideshow",
            category = AiToolCategory.AI_PRESENTATION,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_ai_presentation",
            taskType = AiRouterTaskType.DATA_PRESENTATION,
            systemInstruction = "Create a structured slide-by-slide presentation deck. For each slide include: Slide Title, Key Bullet Points, Visual/Chart Layout Suggestion, and Speaker Notes.",
            inputPlaceholder = "Topic, audience, and slide count (e.g. 10-slide AI Startup Pitch Deck)..."
        ),
        PlatformFeature(
            featureId = "feat_ai_data_analysis",
            name = "AI Data Analyst & KPI Modeler",
            description = "Analyze financial metrics, cohort data, SQL queries, and KPI trends with Markdown tables and statistical insights.",
            howToUse = "Paste CSV/table metrics or business numbers to compute growth rates, anomalies, and strategic recommendations.",
            iconKey = "analytics",
            category = AiToolCategory.AI_DATA_ANALYSIS,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_ai_data_analysis",
            taskType = AiRouterTaskType.DATA_PRESENTATION,
            systemInstruction = "Act as a Staff Data Scientist. Analyze the provided dataset or metrics, present summary tables, trends, outliers, and data-driven recommendations.",
            inputPlaceholder = "Paste dataset rows, KPI numbers, or describe your analysis goal..."
        ),
        PlatformFeature(
            featureId = "feat_ai_web_research",
            name = "AI Competitive & Web Intelligence",
            description = "Live grounded market landscaping, competitor comparisons, and technology radar synthesis.",
            howToUse = "Enter a product domain or company space to generate a live grounded comparison matrix.",
            iconKey = "public",
            category = AiToolCategory.AI_WEB_RESEARCH,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NEW,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent?grounding=googleSearch",
            frontendRoute = "hub://tool/feat_ai_web_research",
            taskType = AiRouterTaskType.SEARCH_RESEARCH,
            systemInstruction = "Use live web search grounding to build an up-to-date market landscape, competitor comparison table, and strategic differentiation analysis.",
            inputPlaceholder = "Enter market sector, product category, or web research topic..."
        ),
        PlatformFeature(
            featureId = "feat_ai_agent",
            name = "Autonomous Goal-Driven AI Agent",
            description = "Decompose complex multi-step objectives into executable sub-tasks, reasoning chains, and verified deliverables.",
            howToUse = "Define a high-level goal. The AI Agent decomposes the objective into phases, executes each step, and compiles the final output.",
            iconKey = "smart_toy",
            category = AiToolCategory.AI_AGENT,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.BETA,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_ai_agent",
            taskType = AiRouterTaskType.AGENT_AUTOMATION,
            systemInstruction = "You are an Autonomous Task Agent. First output [GOAL DECOMPOSITION], then execute [STEP-BY-STEP REASONING & EXECUTION], and conclude with [FINAL DELIVERABLE & VERIFICATION CHECKLIST].",
            inputPlaceholder = "Define your complex multi-step goal for the Autonomous AI Agent..."
        ),
        PlatformFeature(
            featureId = "feat_ai_automation",
            name = "AI Workflow & Automation Builder",
            description = "Design automated pipelines, cron schedules, webhook payloads, and SOP playbooks for business operations.",
            howToUse = "Describe the repetitive process you want to automate to generate trigger-action workflows, scripts, and JSON schemas.",
            iconKey = "account_tree",
            category = AiToolCategory.AI_AUTOMATION,
            version = "2.3.0",
            previousVersion = "2.2.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.EXPERIMENTAL,
            backendEndpoint = "/v1beta/models/gemini-3.1-pro-preview:generateContent",
            frontendRoute = "hub://tool/feat_ai_automation",
            taskType = AiRouterTaskType.AGENT_AUTOMATION,
            systemInstruction = "Design a production-ready automation workflow including Triggers, Conditions, Actions, Retry/Error Handling, and executable script/webhook templates.",
            inputPlaceholder = "Describe the workflow or business process you want to automate..."
        ),
        PlatformFeature(
            featureId = "feat_ai_productivity",
            name = "AI Daily Planner & OKR Strategist",
            description = "Transform goals and backlog items into prioritized time-blocked schedules, OKRs, and sprint plans.",
            howToUse = "List your tasks, deadlines, and available hours to generate a prioritized execution plan.",
            iconKey = "task_alt",
            category = AiToolCategory.AI_PRODUCTIVITY,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "/v1beta/models/gemini-3.5-flash:generateContent",
            frontendRoute = "hub://tool/feat_ai_productivity",
            taskType = AiRouterTaskType.CHAT,
            systemInstruction = "Organize the user's tasks using Eisenhower Matrix prioritization, measurable OKRs, and a realistic time-blocked schedule.",
            inputPlaceholder = "List your goals, tasks, and deadlines..."
        ),
        PlatformFeature(
            featureId = "feat_ai_workspace",
            name = "Kallesh Cloud AI Workspace & Prompt Vault",
            description = "Manage all saved AI artifacts, generated images, videos, music tracks, code snippets, and reusable prompts.",
            howToUse = "Open the Workspace tab to filter, inspect, replay, or export any artifact generated across Kallesh AI Hub.",
            iconKey = "workspaces",
            category = AiToolCategory.AI_WORKSPACE,
            version = "2.3.0",
            previousVersion = "2.1.0",
            status = FeatureStatus.ACTIVE,
            badge = FeatureBadge.NONE,
            backendEndpoint = "firestore://workspace_items",
            frontendRoute = "hub://section/workspace",
            taskType = AiRouterTaskType.CHAT,
            systemInstruction = "Organize and synthesize workspace artifacts.",
            inputPlaceholder = "Search or organize your saved AI workspace artifacts..."
        )
    )
}
